import { Poppins } from "next/font/google";

// Importing your global styles
import "./globals.css";

// Creating a font instance with desired configurations
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

// Exporting metadata and the RootLayout component
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // Applying the font className to the body element
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}